version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    post_build:
      commands:
        - mvn package
artifacts:
  files:
    - target/spaceappspring-0.0.1-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes
